### ISSUE TITLE
Tracking issue of AWS Sigv4 support

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/reqsign#10]
We have essential AWS sigv4 support now, but we need to implement the whole spec of AWS sigv4 so that our users can migrate to reqsign without effect.

- [x] #85
- [ ] Signed payload support
- [x] security token support

**Comment by Xuanwo** [comment]
We can fetch the value from request header `content-md5`.

**Comment by godruoyi** [comment]
But if the user forgets to set this request header, should we generate it automatically based on the body? Or is `hash from the header` the only true source of truth in this package?

**Comment by Xuanwo** [comment]
> But if the user forgets to set this request header, should we generate it automatically based on the body? Or is `hash from the header` the only true source of truth in this package?

The request body may only be consumed once, and users are required to provide it, we can't make decision for them.

**Comment by godruoyi** [comment]
Thank you for your quick reply, it will be much easier to implement now.
