### ISSUE TITLE
Ignore IMDSv2 / metadata check if we are not on aws or gcs

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/reqsign#202]

**Comment by godruoyi** [comment]
hi @Xuanwo My understanding is that we plan to ignore the EC2 Metadata API if the current program is not running on AWS or GCS, but I noticed that we have already added the disable_ec2_metadata attribute. 

https://github.com/godruoyi/reqsign/blob/1abaf124352a678ca7b2286c7218dc99ffc5bfd9/src/aws/credential.rs#L198-L200

Now we can disable calling the EC2 Metadata API by setting with_disable_ec2_metadata. Do we need to do anything else?

**Comment by Xuanwo** [comment]
Yes, users can disable EC2 metadata by setting options.

However, we can improve this process by detecting whether or not we are on AWS or GCS. If we are not on either platform, then we should ignore the call to EC2 metadata since it may hang indefinitely without success.

Unfortunately, there is no reliable way to detect this condition. Some applications attempt to detect it by calling the EC2 metadata API...

**Comment by godruoyi** [comment]
😆, I tried searching and most of the solutions suggest trying to request http://169.254.169.254/latest/meta-data/. My plan is to make a meta-data request first in the load_via_imds_v2 method with a timeout of 2? seconds. If it fails, we will return directly. What do you think?
