### ISSUE TITLE
Create sign builder with explicit config

### ISSUE THREAD

**Issue by wolfv** [Xuanwo/reqsign#237]
The way I understand the code so far, to build a request signer a ConfigLoader is necessary. However, I think it would be interesting for the API to have a way to supply an explicit Config object to the SignerBuilder.

Wouldn't it be better to store a `config` object on the Builder, and do something like

```rust
Signer::builder().config(ConfigLoader::load())

// or with explicit config
Signer::builder().config({
    region: "my-hometown",
    credentials: ...
})
```

Since IIUC the `.load()` call on the ConfigLoader has to be executed by the user anyways.

**Comment by Xuanwo** [comment]
Nice idea! I have did the same thing on aws's builder. We should do this for all services. Maybe we can start with gcs?

**Comment by wolfv** [comment]
yep, will give it a try and then we can port it to the AWS builder if we like it. :)

**Comment by Xuanwo** [comment]
AWS already did this: https://github.com/Xuanwo/reqsign/blob/1f30fd4cea685506c8b6e3dceddc23642a905b59/src/aws/v4.rs#L54-L66

**Comment by wolfv** [comment]
But why not make an additional struct that is just `Config` which would be returned by `ConfigLoader::load() -> Result<Config, ...>`? Then there is no confusion about "loading config" and "providing explicit config".

**Comment by Xuanwo** [comment]
> But why not make an additional struct that is just `Config`

Because I don't want users to access `Config` directly, they should always read/write values via `ConfigLoader`.

**Comment by wolfv** [comment]
I guess then I misunderstood the `ConfigLoader` name and it _is_ basically the `Config` class that I had in mind. I thought it was "only" for loading from disk or environment :)

**Comment by Xuanwo** [comment]
> I guess then I misunderstood the `ConfigLoader` name and it _is_ basically the `Config` class that I had in mind. I thought it was "only" for loading from disk or environment :)

Oh, Naming, is the hardest thing :rofl:
