### ISSUE TITLE
the trait `reqsign::request::SignableRequest` is not implemented for `Request`

### ISSUE THREAD

**Issue by Young-Flash** [Xuanwo/reqsign#251]
I try the example [here](https://docs.rs/reqsign/latest/reqsign/struct.GoogleSigner.html#example) but there is a compile error at `signer.sign(&mut req)?;`, showing: the trait `reqsign::request::SignableRequest` is not implemented for `Request`.
![image](https://user-images.githubusercontent.com/71162630/221399850-3fd506d4-d699-41bd-9142-e161c9899e46.png)

**Comment by Xuanwo** [comment]
Maybe you need to enable feature `reqwest_request`?

**Comment by Young-Flash** [comment]
solved by enable `reqwest_request`, thanks a lot.
