### ISSUE TITLE
azure storage: Allow create SAS token

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/reqsign#301]
https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas

**Comment by godruoyi** [comment]
hi @Xuanwo, I'm interested in this issue now but I have some questions that need to be confirmed, could you please take a look?

I want to implement the SAS token logic in here https://github.com/godruoyi/reqsign/blob/c1e44223a984a612b63c80ee8092f0c089ff62bd/src/azure/storage/signer.rs#L71C1-L73, for my understanding, we should get the necessary parameters from ctx such as `sv/ss/sp/...` first and then build the SAS signature according to the document address above, right?

**Comment by Xuanwo** [comment]
- `sv` is hard coded which is the same version we use for other requests.
- `ss` should be configued by users, we can add a new config `signed_service` for `AzureStorageSigner`. But to make our implement easy, we can start will enable all: `ss=bqtf`
- `srt` is similiar to `ss`, we can start by `srt=sco`
- `sp` is similiar to `ss`, we can start by `sp=rwdlacu`

In a word, we can start by hardcode them :rofl:
