### ISSUE TITLE
AWS: Whether chunked encoding is supported?

### ISSUE THREAD

**Issue by Yaocool** [Xuanwo/reqsign#351]
when set withChunkedEncodingDisabled false, the request body will be chunked encoding and signed in every chunk like this: `20000;chunked-signature=xxxxxx\n chunked value xxx`, does reqsign supports this feature? @Xuanwo 
![image](https://github.com/Xuanwo/reqsign/assets/40883228/1677acce-5f06-41fd-a918-9a41dc0ac579)

**Comment by Xuanwo** [comment]
Not yet.

**Comment by Yaocool** [comment]
> Not yet. reqsign only support single chunk for now.

thanks~ BTW, does any plans about this feature in future?

**Comment by Xuanwo** [comment]
> BTW, does any plans about this feature in future?

Is there a need for any services to use multiple chunk requests? As of now, there is no such plan.

**Comment by Yaocool** [comment]
> > BTW, does any plans about this feature in future?
> 
> Is there a need for any services to use multiple chunk requests? As of now, there is no such plan.

there are many services used multiple chunk requests such as Hadoop and Spark in big data area. They use s3 SDK and set WithChunkedEncodingDisabled to false for uploading faster.

**Comment by Xuanwo** [comment]
> They use s3 SDK and set WithChunkedEncodingDisabled to false for uploading faster.

I don't understand why enabling chunked encoding would make uploading faster. Ideally, it should be slower due to the extra work and padding involved. However, I now understand your use case.
