### ISSUE TITLE
aws: config::Config::from_profile() does not respect AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by nicktp** [Xuanwo/reqsign#381]
I originally raised this issue in [OpenDAL](https://github.com/apache/incubator-opendal/issues/3577) and I was asked by @Xuanwo to post here as a more appropriate place to fix it.  Please refer there to see why it's an issue.  In the context of `reqsign`, it's not really an issue, but more like unintuitive behavior.

Here's the summary:

As a user who uses multiple AWS profiles and switches between them using the `AWS_PROFILE` environment variable, I expect my active profile to be respected.  Currently, when `AwsConfig::default().from_profile()` is called, it will use the profile `default` which I think is unintuitive.

Here are three ways this behavior could be adjusted:
* `from_profile()` could check the current value of the `AWS_PROFILE` environment variable, and use that.  
* `impl Default` could be changed to check `AWS_PROFILE` and fall back to `default`. 
* move to an explicit `AwsConfigBuilder` pattern

Either of the first two could be done with no code changes required from users.  The third might lead to a clearer code, but is more work for everyone.

**Comment by Xuanwo** [comment]
I'd rather resolve this issue initially using the first method, then consider if we can implement the third one. Would you like to help fix it?

**Comment by nicktp** [comment]
Yep - no problem.  I'll get a PR together.
