### ISSUE TITLE
Google account type `impersonated_service_account` not supported

### ISSUE THREAD

**Issue by snowdrop4** [Xuanwo/reqsign#402]
Running the following command to impersonate a service account: `gcloud auth application-default login --impersonate-service-account example@example.com`

This generates a file like:

```json
{
  "delegates": [],
  "service_account_impersonation_url": "xxx",
  "source_credentials": {
    "client_id": "xxx",
    "client_secret": "xxx",
    "refresh_token": "xxx",
    "type": "authorized_user"
  },
  "type": "impersonated_service_account"
}
```

but attempts to read this file results in the following serde error when parsing the JSON:

```
Error("unknown variant `impersonated_service_account`, expected `external_account` or `service_account`", line: 10, column: 40)
```

**Comment by snowdrop4** [comment]
The code I'm using to test is below:

```
async fn debug_gcs() -> Result<(), anyhow::Error> {
    let credential_loader = GoogleCredentialLoader::default()
        .with_path("application_default_credentials.json");

    let credential = credential_loader.load()?.unwrap();

    // Signer will load region and credentials from environment by default.
    let token_loader = GoogleTokenLoader::new(
        "https://www.googleapis.com/auth/devstorage.read_only",
        Client::new(),
    ).with_credentials(credential);

    let signer = GoogleSigner::new("storage");

    // Construct request
    let url = Url::parse("https://storage.googleapis.com/xxx/")?;
    let mut req = reqwest::Request::new(http::Method::GET, url);

    // Signing request with Signer
    let token = token_loader.load().await?.unwrap();
    signer.sign(&mut req, &token)?;

    // Sending already signed request.
    let resp = Client::new().execute(req).await?;
    println!("resp got status: {}", resp.status());

    Ok(())
}
```

**Comment by Xuanwo** [comment]
Thank you for bringing up this issue. Currently, we do not support `impersonated_service_account`. Would you be interested in helping us add this feature?

We could start from here:

https://github.com/Xuanwo/reqsign/blob/8dc135154f1d5e5db4ee3be40d0efacb45c46f7c/src/google/credential.rs#L20-L37

**Comment by snowdrop4** [comment]
Hey. Yeah, if I can help, I will. I'm extremely confused by all the terminology though, and I know literally nothing about google cloud or authentication in general 😅.

I see there's already some mention of impersonated service accounts?

https://github.com/Xuanwo/reqsign/blob/main/src/google/credential/external_account.rs#L38

But that's for impersonated _external_ service accounts? Since it's in the external account file? The google docs for all the different account types are really lacking and I have no idea about the differences between them.

But I take it you're implying that we'd have to add a brand new type like the following?

```
pub struct Credential {
    /// The type of the credential file.
    #[serde(rename = "type")]
    pub ty: CredentialType,

    #[serde(flatten)]
    pub(crate) service_account: Option<ServiceAccount>,
    #[serde(flatten)]
    pub(crate) external_account: Option<ExternalAccount>,
    #[serde(flatten)]
    pub(crate) impersonated_service_account: Option<ImpersonatedServiceAccount>,
}
```

I assume it isn't enough to simply parse the JSON (which is easy enough) though.

**Comment by Xuanwo** [comment]
> But I take it you're implying that we'd have to add a brand new type like the following?

Yes, we can start from here.



> I assume it isn't enough to simply parse the JSON (which is easy enough) though.

Yes, we need to add new token loading logic via `ImpersonatedServiceAccount` too.

**Comment by snowdrop4** [comment]
I'm having a spot of trouble working out what kind of request to send to google.

I have a WIP, and added JSON deserialization and a test and then the beginnings of the token loader: https://github.com/Xuanwo/reqsign/compare/main...snowdrop4:reqsign:AVK/impersonated

I literally can't find the relevant google docs page though. They don't seem to have a page that just tells you how to auth with an impersonated account.

I looked at google's python library and the requests its making when authing an impersonated account, but I can't figure out how exactly it's meant to work either.

It seems like it wants to make a request to the URL `https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/xxx-01-iam@xxx-01.iam.gserviceaccount.com:generateAccessToken:generateIdToken`

with the headers `{'Content-Type': 'application/json', 'x-goog-api-client': 'gl-python/3.11.6 auth/2.23.4 auth-request-type/it cred-type/imp'}`

and then the body `{'audience': 'xxx', 'delegates': [], 'includeEmail': True}`

but I can't figure out what on earth "audience" means (there's no such field in the JSON that google generates). I tried every single possible value from the JSON.

**Comment by Xuanwo** [comment]
> I have a WIP, and added JSON deserialization and a test and then the beginnings of the token loader: [main...snowdrop4:reqsign:AVK/impersonated](https://github.com/Xuanwo/reqsign/compare/main...snowdrop4:reqsign:AVK/impersonated)

Looks like we are very close!

Based the code from google golang oauth2 code, we don't need `audience` in the body:

https://github.com/golang/oauth2/blob/39adbb78078cc1cda488515a968b79fdb2ddb22c/google/internal/externalaccount/impersonate.go#L62-L75

```golang
	reqBody := generateAccessTokenReq{
		Lifetime:  lifetimeString,
		Scope:     its.Scopes,
		Delegates: its.Delegates,
	}
	b, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("oauth2/google: unable to marshal request: %v", err)
	}
	client := oauth2.NewClient(its.Ctx, its.Ts)
	req, err := http.NewRequest("POST", its.URL, bytes.NewReader(b))
	if err != nil {
		return nil, fmt.Errorf("oauth2/google: unable to create impersonation request: %v", err)
	}
```

Mode code could be found at: https://github.com/golang/oauth2/blob/39adbb78078cc1cda488515a968b79fdb2ddb22c/google/google.go#L222

**Comment by snowdrop4** [comment]
Thanks for your infinite patience while I bumble around.

I've never used go, but reading the source, it sent me down the track of using `refresh_token`.

Which lead me to all of these, which seem to more or less agree on how the request should be sent:

- https://fusionauth.io/articles/oauth/complete-list-oauth-grants#flow-for-refresh-token-grant
- https://frontegg.com/blog/oauth-grant-types
- https://github.com/makarski/gauth-rs/blob/main/src/app/mod.rs#L170

I tried following those, and sending a POST with a body with values along the lines of:

```rust
        let req = serde_json::json!({
            "grant_type": "urn:ietf:params:oauth:token-type:refresh_token",
            "refresh_token": &cred.source_credentials.refresh_token,
            "client_id": &cred.source_credentials.client_id,
            "client_secret": &cred.source_credentials.client_secret,
            "scope": [],
        });
```

This seems to match what the docs/other people are doing, but I've had absolutely no luck getting any combination/permutation of this to work. Google returns the same error message every time:

```json
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.iam.credentials.v1.IAMCredentials.GenerateAccessToken",
          "service": "iamcredentials.googleapis.com"
        }
      }
    ]
  }
}
```

I'm at a loss to what I could be doing wrong, and the error message isn't super helpful.

**Comment by Xuanwo** [comment]
> I tried following those, and sending a POST with a body with values along the lines of:

Seems we are mixing two steps here:

First of all, we need to fetch a valid token via `refresh_token`.

Sending this request to `https://oauth2.googleapis.com/token` (I'm not sure if this endpoint is correct):

```rust
      let req = serde_json::json!({
          "grant_type": "urn:ietf:params:oauth:token-type:refresh_token",
          "refresh_token": &cred.source_credentials.refresh_token,
          "client_id": &cred.source_credentials.client_id,
          "client_secret": &cred.source_credentials.client_secret,
          "scope": [],
      });
```

And than, we can use the new token as auth header to send the `generateAccessTokenReq` to `service_account_impersonation_url`:

```go
	reqBody := generateAccessTokenReq{
		Lifetime:  lifetimeString,
		Scope:     its.Scopes,
		Delegates: its.Delegates,
	}
```
