### ISSUE TITLE
azblob request will replace '/' with '%2F' in url 

### ISSUE THREAD

**Issue by D2Lark** [Xuanwo/reqsign#43]
for example
refer [this ](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs)I want list blob by getting this Url `"https://<user>.blob.core.windows.net/<container>?restype=container&comp=list&prefix=/dir"` .But this doesn't work. URL encode '/' to '%2F' like that `"https://<user>.blob.core.windows.net/<container>?restype=container&comp=list&prefix=%2Fdir"` so I use ` path = str::replace(&path, "/", "%2F");`  
mentioned in this [pr](https://github.com/datafuselabs/opendal/pull/165#discussion_r833871571)

**Comment by Xuanwo** [comment]
It's a bit strange to me because `/` is URL safe that don't need to be encoded.

Can you paste the related log by `RUST_LOG=debug cargo test <your-test-case> -- --nocapture
` so that we can figure out what happened?

**Comment by Xuanwo** [comment]
We are closed for not reproducing.
