### ISSUE TITLE
refactor: remove SignableRequest

### ISSUE THREAD

**Issue by flaneur2020** [Xuanwo/reqsign#460]
Thanks a lot for your PR! However I'm thinking of a big refactor that build a `Sign` for entire reqsign. And we can remove the `SignableRequest` concept entirely by just support `http`. Do you have interest in this?

_Originally posted by @Xuanwo in https://github.com/Xuanwo/reqsign/issues/459#issuecomment-2270331094_

**Comment by flaneur2020** [comment]
@Xuanwo can you help assign this issue to me?

**Comment by Xuanwo** [comment]
Great, have fun!
