### ISSUE TITLE
Tencent COS fully supported?

### ISSUE THREAD

**Issue by Yaocool** [Xuanwo/reqsign#504]
Dos Tencent COS signer fully supported? I don't see it stated in the README, but there is actually code for cos. I'm not sure it can use in production env.

**Comment by Yaocool** [comment]
@Xuanwo

**Comment by Xuanwo** [comment]
> Dos Tencent COS signer fully supported? I don't see it stated in the README, but there is actually code for cos. I'm not sure it can use in production env.

Hi, I'm not sure what's `fully supported` means. OpenDAL is using the cos signer and no known issues for now. Please give a try and report issues you meet.

**Comment by Yaocool** [comment]
> > Dos Tencent COS signer fully supported? I don't see it stated in the README, but there is actually code for cos. I'm not sure it can use in production env.
> 
> Hi, I'm not sure what's `fully supported` means. OpenDAL is using the cos signer and no known issues for now. Please give a try and report issues you meet.

okay, I will try it.
